services:
  app1:
    build:
      context: ./app1
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGO_URI=mongodb://arpan:arpan@mongo:27017/app1db?authSource=admin
    depends_on:
      - mongo
    networks:
      - my_network

  app2:
    build:
      context: ./app2
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - MONGO_URI=mongodb://arpan:arpan@mongo:27017/app2db?authSource=admin
    depends_on:
      - mongo
    networks:
      - my_network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: arpan
      MONGO_INITDB_ROOT_PASSWORD: arpan
    volumes:
      - mongo_data:/data/db
    networks:
      - my_network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: arpan
      ME_CONFIG_MONGODB_ADMINPASSWORD: arpan
      ME_CONFIG_MONGODB_URL: mongodb://arpan:arpan@mongo:27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_BASICAUTH_USERNAME: arpan
      ME_CONFIG_BASICAUTH_PASSWORD: arpan
    networks:
      - my_network

volumes:
  mongo_data:

networks:
  my_network:
    driver: bridge
