services:
  admin:
    build:
      context: ./AdminService
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - MONGO_URI=mongodb://dbAdmin:dbPassword@mongo:27017/admin-service?authSource=admin
      - JWT_SECRET=vT96tfSyJqD2tgviU6Mb65W1z
    depends_on:
      - mongo
    networks:
      - microservices

  user:
    build:
      context: ./UserService
    ports:
      - "9000:9000"
    environment:
      - PORT=9000
      - MONGO_URI=mongodb://dbAdmin:dbPassword@mongo:27017/user-service?authSource=admin
      - JWT_SECRET=vT96tfSyJqD2tgviU6Mb65W1z
    depends_on:
      - mongo
    networks:
      - microservices

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: dbAdmin
      MONGO_INITDB_ROOT_PASSWORD: dbPassword
    volumes:
      - db_data:/data/db
    networks:
      - microservices

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: dbAdmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: dbPassword
      ME_CONFIG_MONGODB_URL: mongodb://dbAdmin:dbPassword@mongo:27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_BASICAUTH_USERNAME: test
      ME_CONFIG_BASICAUTH_PASSWORD: test
    networks:
      - microservices

volumes:
  db_data:

networks:
  microservices:
    driver: bridge
